server:
  port: 8080

spring:
  application:
    name: core
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost/seletinha?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
